---
- hosts: all
  tasks:
    - name: check docker container that are running
      command: docker ps
      become: true

    - name: Run a command to run docker nginx container
      command: docker run --name={{ dockername }} -P -d nginx
      become: true

    - name: check docker container that are running
      command: docker ps
      become: true
